# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20161216_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
